##################
# This file is managed by a terraform module that is not located in this repository,
# any changes to this file will be overwritten automatically
##################
name: Secret Sniffer - TruffleHog
description: |
  This workflow runs TruffleHog to detect secrets in the repository.
  It is triggered on every push to the main branch and every pull request.

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Secret Scanning Action
        uses: sdi-one-foundation/trufflehog-secret-sniffer-action@v1
        with:
            ses-username: ${{secrets.FOUNDATION_SES_USERNAME}}
            ses-password: ${{secrets.FOUNDATION_SES_PASSWORD}}
